### ISSUE TITLE
Crucible.get_auth_token() needs error handling

### ISSUE THREAD

**Issue by mattvonrocketstein** [markdrago/banter#5]
See traceback below.  The underlying problem is a 404 in this case, you probably want to use request.raise_for_status().  As a separate question I'm surprised the url (/rest-service/auth-v1/login) 404s.. banter probably needs handshaking to determine whether or not it is compatible with the remote crucible server

[c12067:~/.virtualenvs/PORTALDEV-24925/src/branches/PORTALDEV-24925/iqh] [PORTALDEV-24925] PORTALDEV-24925 ‡ banter --setup
Please enter the URL for crucible: http://crucible05.example.com
Please enter the crucible project key: project
Please enter your crucible username: user
Enter a comma-separated list of usernames for anyone you'd like to include on reviews by default: user
In order to get an auth token from crucible, you must enter your password once.
Password:
Traceback (most recent call last):
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/bin/banter", line 11, in <module>
    sys.exit(main())
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/banter/banter.py", line 16, in main
    setup()
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/banter/banter.py", line 67, in setup
    set_crucible_token(updated_conf)
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/banter/banter.py", line 74, in set_crucible_token
    token = crucible_conn.get_auth_token(conf['crucible']['username'], conf['crucible']['password'])
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/banter/crucible.py", line 14, in get_auth_token
    if response.json() == "" or response.json() is None:
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/simplejson/__init__.py", line 451, in loads
    return _default_decoder.decode(s)
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/simplejson/decoder.py", line 406, in decode
    obj, end = self.raw_decode(s)
  File "/Users/c12067/.virtualenvs/PORTALDEV-24925/lib/python2.7/site-packages/simplejson/decoder.py", line 426, in raw_decode
    raise JSONDecodeError("No JSON object could be decoded", s, idx)
simplejson.decoder.JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)

**Comment by markdrago** [comment]
I like the idea of using requests.raise_for_status().  Would you like to put a patch together that adds that?
